language: python

# Download jadx decompiler
before_script:
  - wget https://github.com/skylot/jadx/releases/download/v0.8.0/jadx-0.8.0.zip -O /tmp/jadx-0.8.0.zip
  - unzip /tmp/jadx-0.8.0.zip -d jadx-0.8.0
  - export PATH=$PATH:$PWD/jadx-0.8.0/bin

python:
  - "3.6"
  - "3.5"
  - "2.7"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - "pip install .[tests,docs]"
# command to run tests
script:
  - nosetests --with-coverage --with-timer --timer-top-n 50
  # Testing the scripts - crude ;)
  - for f in $(find ./ -! -path \*signing\* -name \*.apk); do
      echo "testing $f";
      androsign.py $f > /dev/null || true;
      androaxml.py -i $f > /dev/null || true;
      androaxml.py -i $f -o /dev/null || true;
      androarsc.py -i $f > /dev/null || true;
      androarsc.py -i $f -o /dev/null || true;
      androarsc.py -i $f -t string> /dev/null || true;
      androarsc.py -i $f -t string -o /dev/null || true;
      done
  - python setup.py build_sphinx

notifications:
  email:
    recipients:
      - desnos@t0t0.fr
    on_success: always
    on_failure: always

after_success:
  - codecov
